version: '3'
services:
  redis:
    image: 'redis:latest'
    restart: always
    ports:
      - '6380:6379'
  mongodb:
    image: mongo:4.0
    ports:
      - '27016:27017'
    restart: always
    volumes:
      - mongo-data:/data/db
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
    depends_on:
      - client
      - api
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - '3000:5000'
  api:
    depends_on:
      - mongodb
      - redis
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - '9000:5000'
    environment:
      - APP_HOST=localhost
      - APP_PORT=3050
      - API_PORT=9000
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB=Docker-test
      - REDIS_HOST=redis
      - REDIS_PORT=6379
#networks:
#  my-network:
#    driver: bridge
volumes:
  mongo-data:
