version: "3.7"
services:
  redis-service:
    image: redis
    restart: always
    ports:
      - 6380:6379
    networks:
      - my-network
  node-app:
    build: .
    container_name: nodeapp
    ports:
      - 3000:3000
    environment:
      - MONGO_HOST=server-mongodb
      - MONGO_PORT=27017
      - MONGO_DB=Docker-test
      - REDIS_HOST=redis-service
    depends_on:
      - server-mongodb
    networks:
      - my-network
  server-mongodb:
    image: mongo:4.0
    container_name: mongodb
    ports:
      - 27016:27017
    restart: always
    volumes:
      - mongo-data:/data/db
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
volumes:
  mongo-data:
